# Generated by Django 5.2.2 on 2025-06-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_reviewer',
            field=models.BooleanField(default=False, verbose_name='İnceleme Yetkilisi'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Personel Rolü'),
        ),
    ]
