version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
      - "443:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=www.solutio360.net,solutio360.net
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn solutio_360.wsgi:application --bind 0.0.0.0:8000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/static
      - ./media:/var/www/media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: 