# Generated by Django 5.2.2 on 2025-06-18 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_ml_analysis_complaintcomment_receiver_and_more'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='complaints.complaint', verbose_name='İlişkili Şikayet'),
        ),
        migrations.AddField(
            model_name='report',
            name='ml_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Raporun makine öğrenmesi ile elde edilen analiz sonuçları', verbose_name='Makine Öğrenmesi Analiz Sonuçları'),
        ),
    ]
