# Generated by Django 5.2.2 on 2025-06-18 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ml_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Şikayet metni ve ekleri üzerinde yapılan otomatik analiz sonuçları (duygu, konu, risk vb.)', verbose_name='Makine Öğrenmesi Analiz Sonuçları'),
        ),
        migrations.AddField(
            model_name='complaintcomment',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_comments', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı'),
        ),
        migrations.AddField(
            model_name='complaintcomment',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_comments', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen'),
        ),
    ]
