# Generated by Django 5.2.2 on 2025-06-22 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "complaints",
            "0005_complaint_can_be_withdrawn_complaint_is_withdrawn_and_more",
        ),
        (
            "users",
            "0003_remove_usernotification_users_usern_notific_8ba88d_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaints__categor_82d134_idx",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="ml_analysis",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="ML analysis"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["due_date"], name="complaints__due_dat_3645f4_idx"
            ),
        ),
    ]
