# Generated by Django 5.2.2 on 2025-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0006_remove_complaint_complaints__categor_82d134_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="ml_analysis",
        ),
        migrations.AddField(
            model_name="complaint",
            name="ai_analysis",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="AI analysis"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="ai_processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="AI processed at"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="assigned_department",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="assigned department"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="auto_response",
            field=models.TextField(blank=True, verbose_name="auto response"),
        ),
        migrations.AddField(
            model_name="complaint",
            name="auto_response_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="auto response sent at"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="cultural_context",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="cultural context"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="detected_language",
            field=models.CharField(
                default="tr", max_length=10, verbose_name="detected language"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="emotional_intensity",
            field=models.CharField(
                default="medium", max_length=20, verbose_name="emotional intensity"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalation_path",
            field=models.JSONField(
                blank=True, default=list, verbose_name="escalation path"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="formality_level",
            field=models.CharField(
                default="neutral", max_length=20, verbose_name="formality level"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="routing_confidence",
            field=models.FloatField(
                blank=True, null=True, verbose_name="routing confidence"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="sentiment_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="sentiment score"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="urgency_level",
            field=models.CharField(
                default="medium", max_length=20, verbose_name="urgency level"
            ),
        ),
    ]
