# Generated by Django 5.2.2 on 2025-06-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_alter_complaint_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="can_be_withdrawn",
            field=models.BooleanField(default=True, verbose_name="can be withdrawn"),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_withdrawn",
            field=models.BooleanField(default=False, verbose_name="is withdrawn"),
        ),
        migrations.AddField(
            model_name="complaint",
            name="withdrawal_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="withdrawal date"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="withdrawal_reason",
            field=models.TextField(blank=True, verbose_name="withdrawal reason"),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_REVIEW", "In Review"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REOPENED", "Reopened"),
                    ("CANCELLED", "Cancelled"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="complaintworkflow",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_REVIEW", "In Review"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REOPENED", "Reopened"),
                    ("CANCELLED", "Cancelled"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                max_length=20,
                verbose_name="from status",
            ),
        ),
        migrations.AlterField(
            model_name="complaintworkflow",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_REVIEW", "In Review"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                    ("REOPENED", "Reopened"),
                    ("CANCELLED", "Cancelled"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                max_length=20,
                verbose_name="to status",
            ),
        ),
    ]
