# Simple fix for secret access validation
name: Check Secrets
on: [workflow_call]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has-slack: ${{ steps.check.outputs.has-slack }}
    steps:
      - id: check
        run: |
          if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            echo "has-slack=true" >> $GITHUB_OUTPUT
          else
            echo "has-slack=false" >> $GITHUB_OUTPUT
          fi 